<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <!-- Target .NET 8 with Windows as the target platform -->
	  <TargetFramework>net8.0-windows</TargetFramework>
	  <!-- Specify the target OS version -->
	  <TargetPlatformVersion>10.0.19041.0</TargetPlatformVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="NAudio.WinForms" Version="2.2.1" />
    <PackageReference Include="NAudio.WinMM" Version="2.2.1" />
  </ItemGroup>

</Project>
